- platform: bhyve

#
# automation helpers
#
- platform: template
  sensors:
    hvac_fan_delay:
      value_template: >
        {%- if (states.climate.living_room.attributes.hvac_action == "off") -%}
          102
        {%- else -%}
          48
        {%- endif %}
