title: Bo's House
custom_header:
  exceptions:
    - conditions:
        query_string: "?tablet"
      config:
        compact_mode: true
        disable_sidebar: true
        hide_config: true
        hide_help: true
        hide_raw: true
        hide_unused: true
views:
  # Overview
  - cards:
      - entity: weather.bo_s_house
        type: weather-forecast

      - entities:
          # - entity: light.living_room_lights
          #   type: custom:slider-entity-row
          # - entity: light.kitchen_lights
          #   type: custom:slider-entity-row
          # - entity: light.pendant_lights
          #   type: custom:slider-entity-row
          - entity: light.tall_bulb_1
            type: custom:slider-entity-row
          - entity: light.tall_bulb_2
            type: custom:slider-entity-row
          - entity: light.wingspan
            type: custom:slider-entity-row
        title: Living Room
        type: entities

      - entities:
          - entity: light.bedroom_lamp
            type: custom:slider-entity-row
          # - entity: light.bedside_lamp
          #   type: custom:slider-entity-row
          # - entity: light.bedroom_lights
          #   type: custom:slider-entity-row
        title: Bedroom
        type: entities

      - entities:
          - entity: light.guest_nightstand_1
            type: custom:slider-entity-row
          - entity: light.guest_nightstand_2
            type: custom:slider-entity-row
        title: Guest room
        type: entities
    icon: mdi:home
    path: default_view
    title: Home

  # Climate
  - cards:
      # - entity: climate.floor_bathroom
      #   type: thermostat

      # - entity: climate.floor_studio
      #   type: thermostat

      - type: custom:vertical-stack-in-card
        title: "Living Room"
        cards:
          - type: horizontal-stack
            cards:
              - entity: climate.living_room
                type: thermostat
              - type: custom:mini-graph-card
                name: "Temperature"
                line_width: 2
                aggregate_func: avg
                entities:
                  - sensor.living_room_temperature
                points_per_hour: 2
                show:
                  average: true
                  extrema: true
                  legend: false
                unit: "°F"
                group: false
              - type: custom:mini-graph-card
                name: "Humidity"
                line_width: 2
                entities:
                  - entity: sensor.living_room_humidity
                aggregate_func: avg
                points_per_hour: 2
                show:
                  average: true
                  extrema: true
                  legend: false
                unit: "%"
                group: false

      - type: custom:vertical-stack-in-card
        title: "Hallway"
        cards:
          - type: horizontal-stack
            cards:
              - entity: climate.hallway
                type: thermostat
              - type: custom:mini-graph-card
                name: "Temperature"
                line_width: 2
                entities:
                  - sensor.hallway_temperature
                aggregate_func: avg
                points_per_hour: 2
                show:
                  average: true
                  extrema: true
                  legend: false
                unit: "°F"
                group: false
              - type: custom:mini-graph-card
                name: "Humidity"
                line_width: 2
                entities:
                  - entity: sensor.hallway_humidity
                aggregate_func: avg
                points_per_hour: 2
                show:
                  average: true
                  extrema: true
                  legend: false
                unit: "%"
                group: false

    icon: mdi:snowflake
    path: climate
    title: Climate

  # Media
  - cards:
      - type: custom:mini-media-player
        entity: media_player.living_room_sonos
        artwork: none
        hide:
          power: true

      - type: custom:mini-media-player
        entity: media_player.bedroom_sonos
        artwork: none
        hide:
          power: true

      - type: custom:mini-media-player
        entity: media_player.office_sonos
        artwork: none
        hide:
          power: true
    icon: mdi:cast
    path: media
    title: Media

  # Security
  - cards:
      - entities:
          - binary_sensor.front_door
          - binary_sensor.roof_door
          - binary_sensor.garage_door
          - binary_sensor.window_first_floor_1
          - binary_sensor.window_first_floor_2
          - binary_sensor.window_first_floor_3
          - binary_sensor.window_living_room_5
        show_header_toggle: false
        title: Door/Window Sensors
        type: entities
    icon: mdi:shield-lock
    path: security
    title: Security
